In [1]:
import numpy as np

### １次元配列

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape #一次元配列で三要素

(3,)

### ２次元配列

In [7]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

変形（reshape, ravel, flatten）

In [9]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [11]:
#2×3配列に変換
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
c3=c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [14]:
c4=c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

revel → 参照  
flatten → コピー

データ型(dtype）

In [18]:
d = np.array([1,2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [19]:
d.dtype

dtype('int16')

In [20]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

### インデックスとスライス

１次元配列

In [21]:
a

array([1, 2, 3])

In [22]:
a[0]

1

In [23]:
#スライス
a[1:]

array([2, 3])

In [24]:
a[-1]

3

２次元配列

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b[0]

array([1, 2, 3])

In [28]:
b[1,0] #２行１列目の値

4

In [31]:
b[:,2] #行は全て、列は３列目

array([3, 6])

In [33]:
b[1, :] #行は２行目、列は全て

array([4, 5, 6])

In [34]:
b[0, 1:] #行は１行目、列は２列目以降全て

array([2, 3])

### データ再代入

In [35]:
a

array([1, 2, 3])

In [36]:
a[2]=4
a

array([1, 2, 4])

In [37]:
b

array([[1, 2, 3],
       [4, 5, 6]])